### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by mathstuf** [sardemff7/wayland-notification-area#1]
:)

**Comment by sardemff7** [comment]
Is that required for the MIT licence? The full text is at the top of every relevant file.

Maybe adding a line in the README? :-)

**Comment by mathstuf** [comment]
Fedora wants a file that can be dropped in `/usr/share/licenses/$pkgname`.

**Comment by sardemff7** [comment]
Fixed in 7c2b838e078238d0cb2ebed434aa6c0a93da707d.

**Comment by mathstuf** [comment]
Thanks.

**Comment by sardemff7** [comment]
Btw, releases tarballs are to be found [here](http://download.tuxfamily.org/eventd/wayland-notification-area/).

**Comment by mathstuf** [comment]
OK, thanks.
