### ISSUE TITLE
Support for sway window manager

### ISSUE THREAD

**Issue by vially** [sardemff7/wayland-notification-area#4]
Any plans to support the [sway](https://github.com/SirCmpwn/sway) window manager?

**Comment by sardemff7** [comment]
Yes, I will create a pull request for sway. Half the code is already done, I was waiting for actual need so upstream would be more likely to accept it. :-)

**Comment by vially** [comment]
Awesome, thanks!

**Comment by sardemff7** [comment]
Pull request done: SirCmpwn/sway#644.
